### ISSUE TITLE
What is the reason for this error in the server?

### ISSUE THREAD

**Issue by tongren66** [mfoltz/Bloodcraft#14]
[Error  :Bloody.Core] [02:32:02] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'BloodyWallet, Version=0.1.1.0, Culture=neutral, PublicKeyToken=null'. 绯荤粺鎵句笉鍒版寚瀹氱殑鏂囦欢銆?
File name: 'BloodyWallet, Version=0.1.1.0, Culture=neutral, PublicKeyToken=null'
   at BloodyRewards.Systems.OnlineRewards.OnlineUser(ServerBootstrapSystem sender, NetConnectionId netConnectionId)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Bloody.Core.API.v1.EventsHandlerSystem.OnUserConnectedInvoke(ServerBootstrapSystem sender, NetConnectionId netConnectionId)

**Comment by mfoltz** [comment]
That isn't mine :P make sure you're using the latest version of BloodyCore https://thunderstore.io/c/v-rising/p/Trodi/BloodyCore/
