### ISSUE TITLE
Familiar BUG

### ISSUE THREAD

**Issue by Ulthane** [mfoltz/Bloodcraft#16]
Sometimes this error message appears in the logs and the pets no longer want to spawn.

[Info   :Bloodcraft] Il2CppInterop.Runtime.Il2CppException: System.ArgumentException: The entity does not exist.
--- BEGIN IL2CPP STACK TRACE ---
System.ArgumentException: The entity does not exist.
  at Unity.Entities.EntityComponentStore.AssertEntityHasComponent (Unity.Entities.Entity entity, Unity.Entities.ComponentType componentType) [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.EntityManager.GetComponentDataRawRO (Unity.Entities.Entity entity, Unity.Entities.TypeIndex typeIndex) [0x00000] in <00000000000000000000000000000000>:0 
--- END IL2CPP STACK TRACE ---

   at Il2CppInterop.Runtime.Il2CppException.RaiseExceptionIfNecessary(IntPtr returnedException) in C:\git\v-rising\Il2CppInterop\Il2CppInterop.Runtime\Il2CppException.cs:line 36
   at Unity.Entities.EntityManager.GetComponentDataRawRO(Entity entity, TypeIndex typeIndex)
   at Bloodcraft.ECSExtensions.Read[T](Entity entity)
   at Bloodcraft.Systems.Familiars.FamiliarUnlockSystem.HandleUnitUnlock(Entity killer, Entity died)
   at Bloodcraft.Patches.BuffSpawnSystemPatches.OnUpdatePrefix(BuffSystem_Spawn_Server __instance)

**Comment by mfoltz** [comment]
added a check for that in 0.9.6 (uploading now), reopen issue if it shows up again

**Comment by Ulthane** [comment]
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: Il2CppInterop.Runtime.Il2CppException: System.ArgumentException: A component with type:ProjectM.Shared.DropTableBuffer [Buffer] has not been added to the entity.
--- BEGIN IL2CPP STACK TRACE ---
System.ArgumentException: A component with type:ProjectM.Shared.DropTableBuffer [Buffer] has not been added to the entity.
  at Unity.Entities.EntityComponentStore.AssertEntityHasComponent (Unity.Entities.Entity entity, Unity.Entities.ComponentType componentType) [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.EntityDataAccess.GetBuffer[T] (Unity.Entities.Entity entity, System.Boolean isReadOnly) [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.EntityManager.GetBufferInternal[T] (Unity.Entities.EntityDataAccess* access, Unity.Entities.Entity entity, System.Boolean isReadOnly) [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.EntityManager.GetBuffer[T] (Unity.Entities.Entity entity, System.Boolean isReadOnly) [0x00000] in <00000000000000000000000000000000>:0 
--- END IL2CPP STACK TRACE ---

   at Il2CppInterop.Runtime.Il2CppException.RaiseExceptionIfNecessary(IntPtr returnedException) in C:\git\v-rising\Il2CppInterop\Il2CppInterop.Runtime\Il2CppException.cs:line 36
   at Unity.Entities.EntityManager.GetBuffer[T](Entity entity, Boolean isReadOnly)
   at Bloody.Core.ECSExtensions.ReadBuffer[T](Entity entity)
   at BloodyBoss.DB.Models.BossEncounterModel.ClearDropTable(Entity boss)
   at BloodyBoss.Systems.BossSystem.<>c__DisplayClass5_2.<CheckBoss>b__1()
   at Bloody.Core.API.v1.CoroutineHandler.FrameCoroutine(Action action, Int32 frameInterval, Int32 repeatCount)+MoveNext()
   at Trampoline_ByteThisBepInEx.Unity.IL2CPP.Utils.Collections.Il2CppManagedEnumeratorMoveNext(IntPtr , Il2CppMethodInfo* )


19 / 5 000
Always this message
