### ISSUE TITLE
Internal error in chat command

### ISSUE THREAD

**Issue by Zayats93** [mfoltz/Bloodcraft#17]
After select BloodKnight class, and trying to list class buffs (.lcb chat command), got internal error.
Server logs:

```
[Info   :Bloodstone] [Chat] [Local] Sabien: .clb
[Warning:VampireCommandFramework] Hit unexpected exception executing command listClassBuffs
: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Il2CppInterop.Runtime.Il2CppException: System.ArgumentException: FixedString512Bytes: Truncation while copying "BloodKnight perks: <color=white>AB_BloodBuff_PrimaryAttackLifeLeech PrefabGuid(1828387635)</color> at ╤Г╤А╨╛╨▓╨╡╨╜╤М <color=yellow>22</color>, <color=white>AB_BloodBuff_Creature_RecoverOnKill PrefabGuid(-714434113)</color> at ╤Г╤А╨╛╨▓╨╡╨╜╤М <color=yellow>44</color>, <color=white>AB_BloodBuff_Brute_PhysLifeLeech PrefabGuid(-534491790)</color> at ╤Г╤А╨╛╨▓╨╡╨╜╤М <color=yellow>66</color>, <color=white>AB_BloodBuff_DamageReduction_Creature PrefabGuid(-1055766373)</color> at ╤Г╤А╨╛╨▓╨╡╨╜╤М <color=yellow>88</color>"
--- BEGIN IL2CPP STACK TRACE ---
System.ArgumentException: FixedString512Bytes: Truncation while copying "BloodKnight perks: <color=white>AB_BloodBuff_PrimaryAttackLifeLeech PrefabGuid(1828387635)</color> at ╤Г╤А╨╛╨▓╨╡╨╜╤М <color=yellow>22</color>, <color=white>AB_BloodBuff_Creature_RecoverOnKill PrefabGuid(-714434113)</color> at ╤Г╤А╨╛╨▓╨╡╨╜╤М <color=yellow>44</color>, <color=white>AB_BloodBuff_Brute_PhysLifeLeech PrefabGuid(-534491790)</color> at ╤Г╤А╨╛╨▓╨╡╨╜╤М <color=yellow>66</color>, <color=white>AB_BloodBuff_DamageReduction_Creature PrefabGuid(-1055766373)</color> at ╤Г╤А╨╛╨▓╨╡╨╜╤М <color=yellow>88</color>"
  at Unity.Collections.FixedString512Bytes..ctor (System.String source) [0x00000] in <00000000000000000000000000000000>:0
  at ProjectM.ServerChatUtils.SendSystemMessageToClient (Unity.Entities.EntityManager entityManager, ProjectM.Network.User user, System.String messageText) [0x00000] in <00000000000000000000000000000000>:0
--- END IL2CPP STACK TRACE ---

   at Il2CppInterop.Runtime.Il2CppException.RaiseExceptionIfNecessary(IntPtr returnedException) in C:\git\v-rising\Il2CppInterop\Il2CppInterop.Runtime\Il2CppException.cs:line 36
   at ProjectM.ServerChatUtils.SendSystemMessageToClient(EntityManager entityManager, User user, String messageText)
   at VampireCommandFramework.ChatCommandContext.Reply(String v)
   at Bloodcraft.Services.LocalizationService.HandleReply(ChatCommandContext ctx, String message)
   at Bloodcraft.Commands.LevelingCommands.ClassPerks(ChatCommandContext ctx)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at VampireCommandFramework.CommandRegistry.Handle(ICommandContext ctx, String input)
   
```

**Comment by Zayats93** [comment]
Update:
Have this issue only if set Russian language in setttings. in English all works ok.

**Comment by mfoltz** [comment]
seems the translated message was greater than max chat length possibly, will see about that

**Comment by mfoltz** [comment]
appears fixed in last update.
