### ISSUE TITLE
请问这个问题怎么解决?

### ISSUE THREAD

**Issue by tongren66** [mfoltz/Bloodcraft#21]
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.ArgumentException: An item with the same key has already been added. Key:
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Bloodcraft.Services.PlayerService.CacheUpdateLoop()+MoveNext()
   at Trampoline_ByteThisBepInEx.Unity.IL2CPP.Utils.Collections.Il2CppManagedEnumeratorMoveNext(IntPtr , Il2CppMethodInfo* )

**Comment by mfoltz** [comment]
version?

**Comment by tongren66** [comment]
0.9.8.0

**Comment by mfoltz** [comment]
hmm clearing the cache as it's doing now should be avoiding that but will take another look today

**Comment by mfoltz** [comment]
alright if this isn't fixed now in 0.9.9 I will be baffled but let me know if it happens again lol
