### ISSUE TITLE
Why is this error reported?

### ISSUE THREAD

**Issue by tongren66** [mfoltz/Bloodcraft#22]
[Error  :Il2CppInterop] During invoking native->managed trampoline
Exception: System.TypeInitializationException: The type initializer for 'Bloodcraft.Systems.Experience.LevelingSystem' threw an exception.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Bloodcraft.Systems.Experience.LevelingSystem..cctor()
   --- End of inner exception stack trace ---
   at Bloodcraft.Systems.Experience.LevelingSystem.GetSpellPrefabs()
   at Bloodcraft.Core.Initialize()
   at Bloodcraft.Patches.InitializationPatch.Postfix()
   at DMD<ProjectM.Gameplay.WarEvents.WarEventRegistrySystem::RegisterWarEventEntities>(WarEventRegistrySystem this)
   at (il2cpp -> managed) RegisterWarEventEntities(IntPtr , Il2CppMethodInfo* )

**Comment by mfoltz** [comment]
no idea. will attempt to handle whatever is causing this next version

**Comment by tongren66** [comment]
Okay, I missed a parameter when I localized it. thank you

**Comment by mfoltz** [comment]
should be handled in latest version regardless, sounds good though!
