### ISSUE TITLE
Can't make it to work

### ISSUE THREAD

**Issue by klownk** [mfoltz/Bloodcraft#44]
Hello,
Bloodcraft doesn't work in my solo game.

I have this kind of error at the loading : 
```
[Error  :Bloodcraft] Failed to convert config value for RestedXPRate: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for UnitLevelingMultiplier: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for DocileUnitMultiplier: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for WarEventMultiplier: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for LevelScalingMultiplier: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for LevelingPrestigeReducer: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for PrestigeRatesReducer: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for PrestigeStatMultiplier: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for PrestigeRateMultiplier: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for ExoPrestigeDamageTakenMultiplier: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for MovementSpeed: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for PrimaryAttackSpeed: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for PhysicalLifeLeech: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for SpellLifeLeech: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for PrimaryLifeLeech: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for PhysicalCritChance: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for PhysicalCritDamage: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for SpellCritChance: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for SpellCritDamage: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for PrestigeBloodQuality: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for HealingReceived: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for DamageReduction: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for PhysicalResistance: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for SpellResistance: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for ResourceYield: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for CCReduction: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for SpellCooldownRecoveryRate: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for WeaponCooldownRecoveryRate: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for UltimateCooldownRecoveryRate: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for MinionDamage: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for ShieldAbsorb: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for BloodEfficiency: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for FamiliarPrestigeStatMultiplier: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for UnitFamiliarMultiplier: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for UnitUnlockChance: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for VBloodUnlockChance: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for ShinyChance: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for OnHitProcChance: Input string was not in a correct format.
[Error  :Bloodcraft] Failed to convert config value for StatSynergyMultiplier: Input string was not in a correct format.
```
And in game :
```
[Error  :Il2CppInterop] During invoking native->managed trampoline
Exception: System.TypeInitializationException: The type initializer for 'Bloodcraft.Core' threw an exception.
 ---> System.Exception: There is no Server world (yet)...
   at Bloodcraft.Core..cctor()
   --- End of inner exception stack trace ---
   at Bloodcraft.Patches.UpdateBuffsBufferDestroyPatch.OnUpdatePostix(UpdateBuffsBuffer_Destroy __instance)
   at DMD<ProjectM.UpdateBuffsBuffer_Destroy::OnUpdate>(UpdateBuffsBuffer_Destroy this)
   at (il2cpp -> managed) OnUpdate(IntPtr , Il2CppMethodInfo* )
```

**Comment by klownk** [comment]
You are saying it's not Bloodcraft the problem but something else, that's it?
