### ISSUE TITLE
嗨! 还有个关于血液质量奖励问题

### ISSUE THREAD

**Issue by tongren66** [mfoltz/Bloodcraft#9]
吸取无懒血液后质量100%然后人物属性变得很高，我不知道这个是不是BUG 攻击速度能达到2000%。

**Comment by mfoltz** [comment]
full screenshot of the issue please?

**Comment by tongren66** [comment]
![Uploading 129.png…]()

**Comment by tongren66** [comment]
![Uploading 130.png…]()

**Comment by tongren66** [comment]
![131](https://github.com/mfoltz/Bloodcraft/assets/148411548/8b9d5206-9aee-413c-818e-cee46a898da9)

The new version shows an error after sucking blood:[Error  :Bloodcraft] Exited GameplayEventsSystem hook early: System.DivideByZeroException: Attempted to divide by zero.
   at Bloodcraft.Systems.Experience.LevelingSystem.ApplyClassBuffsAtThresholds(Entity characterEntity, UInt64 SteamID, DebugEventsSystem debugEventsSystem, FromCharacter fromCharacter)
   at Bloodcraft.Systems.Experience.LevelingSystem.CheckAndHandleLevelUp(Entity characterEntity, UInt64 SteamID, Single gainedXP, Int32 currentLevel)
   at Bloodcraft.Systems.Experience.LevelingSystem.ProcessExperienceGain(EntityManager entityManager, Entity killerEntity, Entity victimEntity, UInt64 SteamID, Single groupMultiplier)
   at Bloodcraft.Systems.Experience.LevelingSystem.HandleExperienceUpdate(EntityManager entityManager, Entity killerEntity, Entity victimEntity)
   at Bloodcraft.Patches.CreateGameplayEventOnDestroySystemPatch.OnUpdatePrefix(CreateGameplayEventOnDestroySystem __instance)

**Comment by tongren66** [comment]
![Uploading 131.png…]()

**Comment by mfoltz** [comment]
yeah if you don't have a class selected it will do that atm, need to add a check for that. shouldn't be breaking anything on it's own though

**Comment by mfoltz** [comment]
could you send me the other images in DM on discord? they don't seem to be loading here

**Comment by mfoltz** [comment]
Going to close this for now, think I handled it in 0.9.2 but will revisit if needed
